name: Run Make

on:
  push:
    tags:
      - '*'

jobs:
  install-lua-dependencies:
    runs-on: macos-latest
    strategy:
      matrix:
        lua-version: ['5.3']
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup build environment
      run: |
        mkdir build
        cd build
    
    - name: Build Lua from source
      run: |
        if [[ "${{ matrix.lua-version }}" == "5.3" ]]; then
          curl -L -R -O -v https://www.lua.org/ftp/lua-5.3.6.tar.gz
          tar zxf lua-5.3.6.tar.gz
          cd lua-5.3.6
          make macosx test
        fi

    - name: Setup Lua environment
      run: |
        if [[ "${{ matrix.lua-version }}" == "5.3" ]]; then
          echo "LUAINC=$(pwd)/lua-5.3.6/src" >> $GITHUB_ENV
          echo "LUAEXE=$(pwd)/lua-5.3.6/src/lua" >> $GITHUB_ENV
          echo "LUALIB=$(dirname $(pwd)/lua-5.3.6/src/lua)" >> $GITHUB_ENV
        fi
        
    - name: Run Make and tests
      run: |
        make clean
        make -e
        make test -e

    - name: Archive Lua build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lua-build-artifacts
        path: |
          **/*.so
        if-no-files-found: error
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: |
          **/*.so
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
