name: Run Make

on: [push, pull_request] # Triggers the workflow on push or pull request events

jobs:
  install-lua-dependencies:
    runs-on: macos-latest # Specifies the runner environment
    strategy:
      matrix:
        lua-version: ['5.3', 'jit'] # Specifies Lua versions of interest
    steps:
    - uses: actions/checkout@v3 # Checks out your repository under $GITHUB_WORKSPACE, so the job can access it
    
    # Install Lua and LuaRocks. Replace the following step with specific installation
    # commands fitting each Lua version and the dependency needs of your project.
    - name: Install Lua and LuaRocks
      run: |
        brew install lua@5.3 luarocks # Example for lua5.3
        if [[ "${{ matrix.lua-version }}" == "5.1" ]]; then
          brew install lua@5.1
        elif [[ "${{ matrix.lua-version }}" == "jit" ]]; then
          brew install luajit
        fi
        luarocks install --local luarocks # Adjust as per your Lua version

    - name: Setup Lua environment
      run: |
        if [[ "${{ matrix.lua-version }}" == "5.1" ]]; then
          echo "LUAINC=/usr/local/include/lua5.1" >> $GITHUB_ENV
          echo "LUAEXE=lua5.1" >> $GITHUB_ENV
        elif [[ "${{ matrix.lua-version }}" == "jit" ]]; then
          echo "LUAINC=/usr/local/include/luajit-2.1" >> $GITHUB_ENV
          echo "LUAEXE=luajit" >> $GITHUB_ENV
        else # Assuming the default case is lua 5.3, adjust as necessary
          echo "LUAINC=/usr/local/include/lua5.3" >> $GITHUB_ENV
          echo "LUAEXE=lua" >> $GITHUB_ENV
        fi
        
    - name: Run Make and tests
      run: |
        make clean
        make
        make test
    # Example end
