name: Run Make

on: [push, pull_request]

jobs:
  install-lua-dependencies:
    runs-on: macos-latest
    strategy:
      matrix:
        lua-version: ['5.3']
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup build environment
      run: |
        mkdir build
        cd build
    
    - name: Build Lua from source
      run: |
        if [[ "${{ matrix.lua-version }}" == "5.3" ]]; then
          curl -L -R -O -v https://www.lua.org/ftp/lua-5.3.6.tar.gz
          ls -lh  # Check file size
          file lua-5.3.6.tar.gz  # Verify file type
          tar zxf lua-5.3.6.tar.gz  # Removed 'v' for silent, add back if needed
          cd lua-5.3.6
          make macosx test
        fi

    - name: Setup Lua environment
      run: |
        if [[ "${{ matrix.lua-version }}" == "5.3" ]]; then
          echo "LUAINC=$(pwd)/lua-5.3.6/src" >> $GITHUB_ENV
          # Assuming lua executable is created in src or similar accessible location
          echo "LUAEXE=$(pwd)/lua-5.3.6/src/lua" >> $GITHUB_ENV
          # Calculate and export LUALIB based on LUAEXE path
          echo "LUALIB=$(dirname $(pwd)/lua-5.3.6/src/lua)" >> $GITHUB_ENV
        fi
        
    - name: Run Make and tests
      run: |
        make clean
        make -e
        make test -e
