name: Run Make

on: [push, pull_request]

jobs:
  install-lua-dependencies:
    runs-on: macos-latest
    strategy:
      matrix:
        lua-version: ['5.3', 'jit']
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Lua and LuaRocks
      run: |
        brew install lua@5.3 luarocks
        if [[ "${{ matrix.lua-version }}" == "5.1" ]]; then
          brew install lua@5.1
        elif [[ "${{ matrix.lua-version }}" == "jit" ]]; then
          brew install luajit
        fi
        luarocks install --local luarocks

    - name: Setup Lua environment
      run: |
        if [[ "${{ matrix.lua-version }}" == "5.1" ]]; then
          PREFIX=$(brew --prefix lua@5.1)
          echo "LUAINC=$PREFIX/include/lua5.1" >> $GITHUB_ENV
          echo "LUAEXE=lua5.1" >> $GITHUB_ENV
        elif [[ "${{ matrix.lua-version }}" == "jit" ]]; then
          PREFIX=$(brew --prefix luajit)
          echo "LUAINC=$PREFIX/include/luajit-2.1" >> $GITHUB_ENV
          echo "LUAEXE=luajit" >> $GITHUB_ENV
        else
          PREFIX=$(brew --prefix lua@5.3)
          echo "LUAINC=$PREFIX/include/lua5.3" >> $GITHUB_ENV
          echo "LUAEXE=lua" >> $GITHUB_ENV
        fi
        
    - name: Run Make and tests
      run: |
        make clean
        make -e
        make test -e
