name: Run Make

on: [push, pull_request] # Triggers the workflow on push or pull request events

jobs:
  build:
    runs-on: macos-latest # Specifies the runner environment

    steps:
    - uses: actions/checkout@v3 # Checks out your repository under $GITHUB_WORKSPACE, so the job can access it

    - name: Run make
      run: make
