name: Run Make

on: [push, pull_request]

jobs:
  install-lua-dependencies:
    runs-on: macos-latest
    strategy:
      matrix:
        lua-version: ['5.3', 'jit']
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup build environment
      run: |
        mkdir build
        cd build
    
    - name: Build Lua from source
      run: |
        if [[ "${{ matrix.lua-version }}" == "5.3" ]]; then
          curl -R -O http://www.lua.org/ftp/lua-5.3.6.tar.gz
          tar zxf lua-5.3.6.tar.gz
          cd lua-5.3.6
          make macosx test
        elif [[ "${{ matrix.lua-version }}" == "jit" ]]; then
          git clone https://luajit.org/git/luajit.git
          cd luajit
          git checkout v2.1
          make && make install
        fi

    - name: Setup Lua environment
      run: |
        if [[ "${{ matrix.lua-version }}" == "jit" ]]; then
          echo "LUAINC=$(pwd)/luajit/src" >> $GITHUB_ENV
          echo "LUAEXE=$(pwd)/luajit/src/luajit" >> $GITHUB_ENV
        else
          echo "LUAINC=$(pwd)/lua-5.3.6/src" >> $GITHUB_ENV
          # Assuming lua executable is created in src or similar accessible location
          echo "LUAEXE=$(pwd)/lua-5.3.6/src/lua" >> $GITHUB_ENV
        fi
        
    - name: Run Make and tests
      run: |
        make clean
        make -e
        make test -e
